# --- !Ups
insert into drug values("0135-0135","PANADOL","acetaminophen","TABLET","ORAL");
insert into drug values("0135-0136","PANADOL","acetaminophen","TABLET, FILM COATED","ORAL");
insert into drug values("0135-0140","TUMS","calcium carbonate","TABLET","ORAL");
insert into drug values("0135-0145","NICODERM","nicotine","PATCH, EXTENDED RELEASE","TRANSDERMAL");
insert into drug values("0135-0154","TUMS","calcium carbonate","TABLET","ORAL");
insert into drug values("0135-0157","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0158","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0178","TUMS","calcium carbonate","TABLET","ORAL");
insert into drug values("0135-0180","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0181","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0194","NICODERM","nicotine","PATCH, EXTENDED RELEASE","TRANSDERMAL");
insert into drug values("0135-0195","NICODERM","nicotine","PATCH, EXTENDED RELEASE","TRANSDERMAL");
insert into drug values("0135-0196","NICODERM","nicotine","PATCH, EXTENDED RELEASE","TRANSDERMAL");
insert into drug values("0135-0199","CITRUCEL","methylcellulose","TABLET","ORAL");
insert into drug values("0135-0200","ABREVA","docosanol","CREAM","TOPICAL");
insert into drug values("0135-0201","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0225","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0226","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0228","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0229","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0230","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0234","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0241","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0242","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0243","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0245","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0246","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0355","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0430","Gaviscon","aluminum hydroxide and magnesium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0432","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0435","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0456","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0460","SENSODYNE PRONAMEL","potassium nitrate and sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0461","ALLI","orlistat","CAPSULE","ORAL");
insert into drug values("0135-0466","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0467","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0468","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0469","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0473","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0474","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0475","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0484","SENSODYNE PRONAMEL","potassium nitrate and sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0487","BIOTENE","sodium monofluorophosphate","PASTE","ORAL");
insert into drug values("0135-0508","NICORETTE","nicotine polacrilex","LOZENGE","ORAL");
insert into drug values("0135-0509","NICORETTE","nicotine polacrilex","LOZENGE","ORAL");
insert into drug values("0135-0510","NICORETTE","nicotine polacrilex","LOZENGE","ORAL");
insert into drug values("0135-0511","NICORETTE","nicotine polacrilex","LOZENGE","ORAL");
insert into drug values("0135-0512","NICORETTE","nicotine polacrilex","LOZENGE","ORAL");
insert into drug values("0135-0513","NICORETTE","nicotine polacrilex","LOZENGE","ORAL");
insert into drug values("0135-0514","NICORETTE","nicotine polacrilex","LOZENGE","ORAL");
insert into drug values("0135-0515","NICORETTE","nicotine polacrilex","LOZENGE","ORAL");
insert into drug values("0135-0520","SENSODYNE PRONAMEL","potassium nitrate and sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0521","TUMS","calcium carbonate","TABLET","ORAL");
insert into drug values("0135-0522","Tums","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0523","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0525","Sensodyne","potassium nitrate and sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0526","Sensodyne","potassium nitrate and sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0527","Sensodyne","potassium nitrate and sodium fluoride","GEL","DENTAL");
insert into drug values("0135-0528","Sensodyne","potassium nitrate and sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0529","Sensodyne","potassium nitrate and sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0531","Aquafresh","sodium monofluorophosphate","PASTE","DENTAL");
insert into drug values("0135-0532","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0533","Nicorette","nicotine polacrilex","GUM, CHEWING","ORAL");
insert into drug values("0135-0534","Aquafresh","sodium monofluorophosphate","PASTE","DENTAL");
insert into drug values("0135-0537","PANADOL","acetaminophen","SUSPENSION","ORAL");
insert into drug values("0135-0539","PANADOL","acetaminophen","SUSPENSION","ORAL");
insert into drug values("0135-0540","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0541","Tums","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0544","Aquafresh Big Kids","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0547","SENSODYNE","stannous fluoride","PASTE","ORAL");
insert into drug values("0135-0548","SENSODYNE","stannous fluoride","PASTE","ORAL");
insert into drug values("0135-0550","Sensodyne","potassium nitrate and sodium fluoride","GEL","DENTAL");
insert into drug values("0135-0551","Sensodyne","potassium nitrate and sodium fluoride","GEL","DENTAL");
insert into drug values("0135-0557","BIOTENE","sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0558","BIOTENE","sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0560","Tums","calcium carbonate","BAR, CHEWABLE","ORAL");
insert into drug values("0135-0561","Tums","calcium carbonate","BAR, CHEWABLE","ORAL");
insert into drug values("0135-0563","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0564","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0568","SENSODYNE PRONAMEL","potassium nitrate and sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0569","Tums","calcium carbonate","BAR, CHEWABLE","ORAL");
insert into drug values("0135-0572","Sensodyne Complete Protection","stannous fluoride","PASTE","DENTAL");
insert into drug values("0135-0573","Sensodyne Complete Protection","stannous fluoride","PASTE","DENTAL");
insert into drug values("0135-0574","GAVISCON","aluminum hydroxide and magnesium carbonate","LIQUID","ORAL");
insert into drug values("0135-0575","SENSODYNE","stannous fluoride","PASTE","ORAL");
insert into drug values("0135-0576","FLONASE","fluticasone propionate","SPRAY, METERED","NASAL");
insert into drug values("0135-0577","biotene","sodium monofluorophosphate","PASTE","ORAL");
insert into drug values("0135-0579","Sensodyne","potassium nitrate and sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0581","Sensodyne","potassium nitrate and sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0582","CHILDRENS FLONASE","fluticasone propionate","SPRAY, METERED","NASAL");
insert into drug values("0135-0586","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0588","SENSODYNE PRONAMEL","sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0589","Nicorette and Aquafresh","nicotine polacrilex and sodium fluoride","KIT","");
insert into drug values("0135-0590","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0591","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0592","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0593","sensodyne","potassium nitrate and sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0594","AQUAFRESH","sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0598","parodontax","stannous fluoride","PASTE","DENTAL");
insert into drug values("0135-0599","parodontax","stannous fluoride","PASTE","DENTAL");
insert into drug values("0135-0601","parodontax","stannous fluoride","PASTE","DENTAL");
insert into drug values("0135-0602","Sensodyne Pronamel","potassium nitrate and sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0603","Sensodyne Pronamel","potassium nitrate and sodium fluoride","PASTE","ORAL");
insert into drug values("0135-0605","AQUAFRESH","potassium nitrate and sodium fluoride","PASTE","DENTAL");
insert into drug values("0135-0606","Tums Chewy Bites","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0607","Panadol","acetaminophen and phenyleprine HCl","TABLET, FILM COATED","ORAL");
insert into drug values("0135-0608","PANADOL","acetaminophen and diphenhydramine HCl","TABLET, FILM COATED","ORAL");
insert into drug values("0135-0609","PANADOL","acetaminophen","TABLET, FILM COATED","ORAL");
insert into drug values("0135-0610","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0611","Tums","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0612","TUMS","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0615","FLONASE SENSIMIST","fluticasone furoate","SPRAY, METERED","NASAL");
insert into drug values("0135-0616","FLONASE SENSIMIST","fluticasone furoate","SPRAY, METERED","NASAL");
insert into drug values("0135-0618","Tums Chewy Bites","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0135-0620","PANADOL","acetaminophen and caffeine","TABLET, FILM COATED","ORAL");
insert into drug values("0135-0621","SENSODYNE","stannous fluoride","PASTE","ORAL");
insert into drug values("0135-0622","SENSODYNE","stannous fluoride","PASTE","ORAL");
insert into drug values("0135-0623","Tums Chewy Bites","calcium carbonate","TABLET, CHEWABLE","ORAL");
insert into drug values("0140-0004","Valium","diazepam","TABLET","ORAL");
insert into drug values("0140-0005","Valium","diazepam","TABLET","ORAL");
insert into drug values("0140-0006","Valium","diazepam","TABLET","ORAL");
insert into drug values("0143-0170","Butalbital, Acetaminophen, and Caffeine","Butalbital, Acetaminophen, and Caffeine","CAPSULE","ORAL");
insert into drug values("0143-1140","Belladonna Alkaloids with Phenobarbital","Belladonna Alkaloids with Phenobarbital","TABLET","ORAL");
insert into drug values("0143-1171","Captopril","Captopril","TABLET","ORAL");
insert into drug values("0143-1172","Captopril","Captopril","TABLET","ORAL");
insert into drug values("0143-1173","Captopril","Captopril","TABLET","ORAL");
insert into drug values("0143-1174","Captopril","Captopril","TABLET","ORAL");
insert into drug values("0143-1176","Carisoprodol","Carisoprodol","TABLET","ORAL");
insert into drug values("0143-1195","Chloroquine","Chloroquine Phosphate","TABLET","ORAL");
insert into drug values("0143-1202","Cortisone Acetate","Cortisone Acetate","TABLET","ORAL");
insert into drug values("0143-1209","Chlorothiazide","Chlorothiazide","TABLET","ORAL");
insert into drug values("0143-1210","Chlorothiazide","Chlorothiazide","TABLET","ORAL");
insert into drug values("0143-1227","Dicyclomine","Dicyclomine Hydrochloride","TABLET","ORAL");
insert into drug values("0143-1240","Digoxin","Digoxin","TABLET","ORAL");
insert into drug values("0143-1241","Digoxin","Digoxin","TABLET","ORAL");
insert into drug values("0143-1246","Fludrocortisone Acetate","Fludrocortisone Acetate","TABLET","ORAL");
insert into drug values("0143-1250","Glycopyrrolate","Glycopyrrolate","TABLET","ORAL");
insert into drug values("0143-1251","Glycopyrrolate","Glycopyrrolate","TABLET","ORAL");
insert into drug values("0143-1252","Hydrocortisone","Hydrocortisone","TABLET","ORAL");
insert into drug values("0143-1253","Hydrocortisone","Hydrocortisone","TABLET","ORAL");
insert into drug values("0143-1254","Hydrocortisone","Hydrocortisone","TABLET","ORAL");
insert into drug values("0143-1256","Hydrochlorothiazide","Hydrochlorothiazide","TABLET","ORAL");
insert into drug values("0143-1257","Hydrochlorothiazide","Hydrochlorothiazide","TABLET","ORAL");
insert into drug values("0143-1260","Isoniazid","Isoniazid","TABLET","ORAL");
insert into drug values("0143-1261","Isoniazid","Isoniazid","TABLET","ORAL");
insert into drug values("0143-1262","Lisinopril with Hydrochlorothiazide","Lisinopril and Hydrochlorothiazide","TABLET","ORAL");
insert into drug values("0143-1263","Lisinopril with Hydrochlorothiazide","Lisinopril and Hydrochlorothiazide","TABLET","ORAL");
insert into drug values("0143-1264","Lisinopril with Hydrochlorothiazide","Lisinopril and Hydrochlorothiazide","TABLET","ORAL");
insert into drug values("0143-1266","Lisinopril","Lisinopril","TABLET","ORAL");
insert into drug values("0143-1267","Lisinopril","Lisinopril","TABLET","ORAL");
insert into drug values("0143-1268","Lisinopril","Lisinopril","TABLET","ORAL");
insert into drug values("0143-1270","Lisinopril","Lisinopril","TABLET","ORAL");
insert into drug values("0143-1277","Lithium Carbonate","Lithium Carbonate","TABLET, EXTENDED RELEASE","ORAL");
insert into drug values("0143-1282","Mefloquine Hydrochloride","Mefloquine Hydrochloride","TABLET","ORAL");
insert into drug values("0143-1290","Methocarbamol","Methocarbamol","TABLET","ORAL");
insert into drug values("0143-1292","Methocarbamol","Methocarbamol","TABLET","ORAL");
insert into drug values("0143-1300","Lithium Carbonate","Lithium Carbonate","TABLET","ORAL");
insert into drug values("0143-1333","Isosorbide Mononitrate","Isosorbide Mononitrate","TABLET, COATED","ORAL");
insert into drug values("0143-1346","Naproxen","Naproxen","TABLET","ORAL");
insert into drug values("0143-1347","Naproxen","Naproxen","TABLET","ORAL");
# --- !Downs
DELETE FROM drug;
