# --- !Ups
insert into diagnosis values("Z91010","Allergy to peanuts");
insert into diagnosis values("Z91011","Allergy to milk products");
insert into diagnosis values("Z91012","Allergy to eggs");
insert into diagnosis values("Z91013","Allergy to seafood"); 
insert into diagnosis values("Z91018","Allergy to other foods");
insert into diagnosis values("Z9102","Food additives allergy status");
insert into diagnosis values("Z91030","Bee allergy status");
insert into diagnosis values("Z91038","Other insect allergy status");
insert into diagnosis values("Z91040","Latex allergy status");
insert into diagnosis values("Z91041","Radiographic dye allergy status");
insert into diagnosis values("Z91048","Other nonmedicinal substance allergy status");
insert into diagnosis values("Z9109","Other allergy status, other than to drugs and biological substances");
insert into diagnosis values("Z9111","Patient's noncompliance with dietary regimen");
insert into diagnosis values("Z91120","Patient's intentional underdosing of medication regimen due to financial hardship");
insert into diagnosis values("Z91128","Patient's intentional underdosing of medication regimen for other reason");
insert into diagnosis values("Z91130","Patient's unintentional underdosing of medication regimen due to age-related debility");
insert into diagnosis values("Z91138","Patient's unintentional underdosing of medication regimen for other reason");
insert into diagnosis values("Z9114","Patient's other noncompliance with medication regimen");
insert into diagnosis values("Z9115","Patient's noncompliance with renal dialysis");
insert into diagnosis values("Z9119","Patient's noncompliance with other medical treatment and regimen");
insert into diagnosis values("Z91410","Personal history of adult physical and sexual abuse");
insert into diagnosis values("Z91411","Personal history of adult psychological abuse");
insert into diagnosis values("Z91412","Personal history of adult neglect");
insert into diagnosis values("Z91419","Personal history of unspecified adult abuse");
insert into diagnosis values("Z9149","Other personal history of psychological trauma, not elsewhere classified");
insert into diagnosis values("Z915","Personal history of self-harm");
insert into diagnosis values("Z9181","History of falling");
insert into diagnosis values("Z9182","Personal history of military deployment");
insert into diagnosis values("Z9183","Wandering in diseases classified elsewhere");
insert into diagnosis values("Z9189","Other specified personal risk factors, not elsewhere classified");
insert into diagnosis values("Z920","Personal history of contraception");
insert into diagnosis values("Z9221","Personal history of antineoplastic chemotherapy");
insert into diagnosis values("Z9222","Personal history of monoclonal drug therapy");
insert into diagnosis values("Z9223","Personal history of estrogen therapy");
insert into diagnosis values("Z92240","Personal history of inhaled steroid therapy");
insert into diagnosis values("Z92241","Personal history of systemic steroid therapy");
insert into diagnosis values("Z9225","Personal history of immunosupression therapy");
insert into diagnosis values("Z9229","Personal history of other drug therapy");
insert into diagnosis values("Z923","Personal history of irradiation");
insert into diagnosis values("Z9281","Personal history of extracorporeal membrane oxygenation (ECMO)");
insert into diagnosis values("Z9282","Status post administration of tPA (rtPA) in a different facility within the last 24 hours prior to admission to current facility");
insert into diagnosis values("Z9283","Personal history of failed moderate sedation");
insert into diagnosis values("Z9284","Personal history of unintended awareness under general anesthesia");
insert into diagnosis values("Z9289","Personal history of other medical treatment");
insert into diagnosis values("Z930","Tracheostomy status");
insert into diagnosis values("Z931","Gastrostomy status");
insert into diagnosis values("Z932","Ileostomy status");
insert into diagnosis values("Z933","Colostomy status");
insert into diagnosis values("Z934","Other artificial openings of gastrointestinal tract status");
insert into diagnosis values("Z9350","Unspecified cystostomy status");
insert into diagnosis values("Z9351","Cutaneous-vesicostomy status");
insert into diagnosis values("Z9352","Appendico-vesicostomy status");
insert into diagnosis values("Z9359","Other cystostomy status");
insert into diagnosis values("Z936","Other artificial openings of urinary tract status");
insert into diagnosis values("Z938","Other artificial opening status");
insert into diagnosis values("Z939","Artificial opening status, unspecified");
insert into diagnosis values("Z940","Kidney transplant status");
insert into diagnosis values("Z941","Heart transplant status");
insert into diagnosis values("Z942","Lung transplant status");
insert into diagnosis values("Z943","Heart and lungs transplant status");
insert into diagnosis values("Z944","Liver transplant status");
insert into diagnosis values("Z945","Skin transplant status");
insert into diagnosis values("Z946","Bone transplant status");
insert into diagnosis values("Z947","Corneal transplant status");
insert into diagnosis values("Z9481","Bone marrow transplant status");
insert into diagnosis values("Z9482","Intestine transplant status");
insert into diagnosis values("Z9483","Pancreas transplant status");
insert into diagnosis values("Z9484","Stem cells transplant status");
insert into diagnosis values("Z9489","Other transplanted organ and tissue status");
insert into diagnosis values("Z949","Transplanted organ and tissue status, unspecified");
insert into diagnosis values("Z950","Presence of cardiac pacemaker");
insert into diagnosis values("Z951","Presence of aortocoronary bypass graft");
insert into diagnosis values("Z952","Presence of prosthetic heart valve");
insert into diagnosis values("Z953","Presence of xenogenic heart valve");
insert into diagnosis values("Z954","Presence of other heart-valve replacement");
insert into diagnosis values("Z955","Presence of coronary angioplasty implant and graft");
insert into diagnosis values("Z95810","Presence of automatic (implantable) cardiac defibrillator");
insert into diagnosis values("Z95811","Presence of heart assist device");
insert into diagnosis values("Z95812","Presence of fully implantable artificial heart");
insert into diagnosis values("Z95818","Presence of other cardiac implants and grafts");
insert into diagnosis values("Z95820","Peripheral vascular angioplasty status with implants and grafts");
insert into diagnosis values("Z95828","Presence of other vascular implants and grafts");
insert into diagnosis values("Z959","Presence of cardiac and vascular implant and graft, unspecified");
insert into diagnosis values("Z960","Presence of urogenital implants");
insert into diagnosis values("Z961","Presence of intraocular lens");
insert into diagnosis values("Z9620","Presence of otological and audiological implant, unspecified");
insert into diagnosis values("Z9621","Cochlear implant status");
insert into diagnosis values("Z9622","Myringotomy tube(s) status");
insert into diagnosis values("Z9629","Presence of other otological and audiological implants");
insert into diagnosis values("Z963","Presence of artificial larynx");
insert into diagnosis values("Z9641","Presence of insulin pump (external) (internal)");
insert into diagnosis values("Z9649","Presence of other endocrine implants");
insert into diagnosis values("Z965","Presence of tooth-root and mandibular implants");
insert into diagnosis values("Z9660","Presence of unspecified orthopedic joint implant");
insert into diagnosis values("Z96611","Presence of right artificial shoulder joint");
insert into diagnosis values("Z96612","Presence of left artificial shoulder joint");
insert into diagnosis values("Z96619","Presence of unspecified artificial shoulder joint");
insert into diagnosis values("Z96621","Presence of right artificial elbow joint");
insert into diagnosis values("Z96622","Presence of left artificial elbow joint");
insert into diagnosis values("Z96629","Presence of unspecified artificial elbow joint");
insert into diagnosis values("Z96631","Presence of right artificial wrist joint");
insert into diagnosis values("Z96632","Presence of left artificial wrist joint");
insert into diagnosis values("Z96639","Presence of unspecified artificial wrist joint");
insert into diagnosis values("Z96641","Presence of right artificial hip joint");
insert into diagnosis values("Z96642","Presence of left artificial hip joint");
insert into diagnosis values("Z96643","Presence of artificial hip joint, bilateral");
insert into diagnosis values("Z96649","Presence of unspecified artificial hip joint");
insert into diagnosis values("Z96651","Presence of right artificial knee joint");
insert into diagnosis values("Z96652","Presence of left artificial knee joint");
insert into diagnosis values("Z96653","Presence of artificial knee joint, bilateral");
insert into diagnosis values("Z96659","Presence of unspecified artificial knee joint");
insert into diagnosis values("Z96661","Presence of right artificial ankle joint");
insert into diagnosis values("Z96662","Presence of left artificial ankle joint");
insert into diagnosis values("Z96669","Presence of unspecified artificial ankle joint");
insert into diagnosis values("Z96691","Finger-joint replacement of right hand");
insert into diagnosis values("Z96692","Finger-joint replacement of left hand");
insert into diagnosis values("Z96693","Finger-joint replacement, bilateral");
insert into diagnosis values("Z96698","Presence of other orthopedic joint implants");
insert into diagnosis values("Z967","Presence of other bone and tendon implants");
insert into diagnosis values("Z9681","Presence of artificial skin");
insert into diagnosis values("Z9689","Presence of other specified functional implants");
insert into diagnosis values("Z969","Presence of functional implant, unspecified");
insert into diagnosis values("Z970","Presence of artificial eye");
insert into diagnosis values("Z9710","Presence of artificial limb (complete) (partial), unspecified");
insert into diagnosis values("Z9711","Presence of artificial right arm (complete) (partial)");
insert into diagnosis values("Z9712","Presence of artificial left arm (complete) (partial)");
insert into diagnosis values("Z9713","Presence of artificial right leg (complete) (partial)");
insert into diagnosis values("Z9714","Presence of artificial left leg (complete) (partial)");
insert into diagnosis values("Z9715","Presence of artificial arms, bilateral (complete) (partial)");
insert into diagnosis values("Z9716","Presence of artificial legs, bilateral (complete) (partial)");
insert into diagnosis values("Z972","Presence of dental prosthetic device (complete) (partial)");
insert into diagnosis values("Z973","Presence of spectacles and contact lenses");
insert into diagnosis values("Z974","Presence of external hearing-aid");
insert into diagnosis values("Z975","Presence of (intrauterine) contraceptive device");
insert into diagnosis values("Z978","Presence of other specified devices");
insert into diagnosis values("Z980","Intestinal bypass and anastomosis status");
insert into diagnosis values("Z981","Arthrodesis status");
insert into diagnosis values("Z982","Presence of cerebrospinal fluid drainage device");
insert into diagnosis values("Z983","Post therapeutic collapse of lung status");
insert into diagnosis values("Z9841","Cataract extraction status, right eye");
insert into diagnosis values("Z9842","Cataract extraction status, left eye");
insert into diagnosis values("Z9849","Cataract extraction status, unspecified eye");
insert into diagnosis values("Z9851","Tubal ligation status");
insert into diagnosis values("Z9852","Vasectomy status");
insert into diagnosis values("Z9861","Coronary angioplasty status");
insert into diagnosis values("Z9862","Peripheral vascular angioplasty status");
insert into diagnosis values("Z98810","Dental sealant status");
insert into diagnosis values("Z98811","Dental restoration status");
insert into diagnosis values("Z98818","Other dental procedure status");
insert into diagnosis values("Z9882","Breast implant status");
insert into diagnosis values("Z9883","Filtering (vitreous) bleb after glaucoma surgery status");
insert into diagnosis values("Z9884","Bariatric surgery status");
insert into diagnosis values("Z9885","Transplanted organ removal status");
insert into diagnosis values("Z9886","Personal history of breast implant removal");
insert into diagnosis values("Z98870","Personal history of in utero procedure during pregnancy");
insert into diagnosis values("Z98871","Personal history of in utero procedure while a fetus");
insert into diagnosis values("Z98890","Other specified postprocedural states");
insert into diagnosis values("Z98891","History of uterine scar from previous surgery");
insert into diagnosis values("Z990","Dependence on aspirator");
insert into diagnosis values("Z9911","Dependence on respirator [ventilator] status");
insert into diagnosis values("Z9912","Encounter for respirator [ventilator] dependence during power failure");
insert into diagnosis values("Z992","Dependence on renal dialysis");
insert into diagnosis values("Z993","Dependence on wheelchair");
insert into diagnosis values("Z9981","Dependence on supplemental oxygen");
insert into diagnosis values("Z9989","Dependence on other enabling machines and devices");
# --- !Downs
DELETE FROM diagnosis;
